# Generated by Django 3.2.5 on 2021-10-10 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_alter_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='posts',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
