# Generated by Django 3.2.5 on 2021-10-10 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20211010_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Article',
        ),
    ]
